apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: fastapi-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fastapi-role-binding
subjects:
- kind: ServiceAccount
  name: fastapi-sa
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io