name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests #Assuming we have a tests/ folder with pytest-compatible test files
      run: |
        pytest tests/ 

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t just-registry/fastapi:${{ github.sha }} .

    - name: Push Docker image
      run: docker push just-registry/fastapi:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: kubectl apply -f Kubernetes/ 
