name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: docker build -t just-registry/fastapi:${{ github.sha }} .
    - name: Push
      run: docker push just-registry/fastapi:${{ github.sha }}
    - name: Deploy
      run: |
        kubectl apply -f k8s/
